[package]
name = "tamashi"
edition = "2024.beta"
license = "CC-BY-NC-4.0/CC-BY-NC-ND-4.0"
authors = ["Studio Mirai (dev@sm.xyz)"]

[dependencies]

[addresses]
tamashi = "0x0"
admin = "0xde0053243f3226649701a7fe2c3988be11941bf3ff3535f3c8c5bf32fc600220"